pipeline:
  lint:
    when:
      event:
      - push
      - pull_request
    image: node:14
    commands:
    - git config --global url."https://github.com/".insteadOf git://github.com/
    - yarn
    - yarn lint

  test:
    when:
      event:
      - push
      - pull_request
    image: node:14
    commands:
    - apt update
    - apt install firefox-esr -y --no-install-recommends
    - git config --global url."https://github.com/".insteadOf git://github.com/

    - yarn 
    - yarn test

  build:
    when:
      event:
      - tag
    image: node:14
    commands:
    - git config --global url."https://github.com/".insteadOf git://github.com/ 
    - yarn
    - yarn build:prod

  release:
    when:
      event:
      - tag
    image: node:14
    secrets:
    - SCW_ACCESS_KEY
    - SCW_SECRET_KEY
    - SCW_DEFAULT_ORGANIZATION_ID
    commands:
      - apt-get update && apt-get install -y rclone wget zip
      - wget https://github.com/scaleway/scaleway-cli/releases/download/v2.5.1/scaleway-cli_2.5.1_linux_amd64
      - mv scaleway-cli_2.5.1_linux_amd64 scaleway-cli
      - chmod +x scaleway-cli
      - ./scaleway-cli object config install type=rclone
      - zip admin-fe.zip -r dist
      - rclone copyto admin-fe.zip scaleway:akkoma-updates/frontend/admin-fe.zip
